config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admins 
  devise_scope :cashier do
    authenticated :cashier do
      root 'orders#main' , as: :authenticated_roots
      
      resources :orders do
                collection do
                  post :summary, to: 'orders#order_save'
                end
              end
              
          get 'orderlines/index'
              resources :orderlines
              
        unauthenticated do 
	        root 'devise/sessions#landing_page', as: :unauthenticated_roots
        end

    end
  end
 
 
    devise_scope :admin do
      authenticated :admin do
        root 'admins#index', as: :authenticated_root
    
        get 'admin/index'
          resources :admins
          
        #get 'cashiers/transactions'
          resources :orders
          
        get 'cashiers/daily_report'
          resources :orders
          
        get 'products/create_products' #if not working ~> change to admings
          resources :products
           
        get 'cashiers/create'
          resources :cashiers
        
        end
      end
    unauthenticated do 
	    root 'devise/sessions#landing_page', as: :unauthenticated_root
    end

    
    devise_for :cashier
      # devise_scope :cashier do
      #   authenticated :cashier do
      #     root 'orders#main' , as: :authenticated_roots 
        
      #         resources :orders do
      #           collection do
      #             post :summary, to: 'orders#order_save'
      #           end
      #         end
              
      #     get 'orderlines/index'
      #         resources :orderlines
              
      #   unauthenticated do 
	     #   root 'devise/sessions#landing_page', as: :unauthenticated_roots
      #   end

              
      #   end
      # end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  has_many :cashiers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
has_many :orders
has_many :orderlines
         
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cashier
  has_many :products
  has_many :orderlines
  accepts_nested_attributes_for :cashier, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :orderlines, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true
  
  def to_s
    product_name
  end
end

app/models/orderline.rb
class Orderline < ApplicationRecord
  belongs_to :product
  belongs_to :order
  belongs_to :cashier
  has_many :products
  
  def total_price
  end
  def to_s
      total_price.to_f
  end
  def sub_total
      # sub_total = quantity + price 
  end
  def total
  end
end

app/models/product.rb
class Product < ApplicationRecord
    #belongs_to :admin
     #has_many :orders 
    has_many :orderlines
    
    def to_s
        product_name
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  before_action :set_cashier, only: [:show, :edit, :update, :destroy, :transactions]
  
  def index
    @cashiers = Cashier.all
  end
  
  def new
    @cashier = Cashier.new
  end
  
  def create
    @cashier = Cashier.new(cashier_name: cashier_params["cashier_name"], cashier_status: true, admin_id: current_admin.id, password: "password", email: cashier_params["email"]) #check
    # raise @cashier.inspect
    if @cashier.save
      redirect_to @cashier
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def daily_report
    @orders = Order.all
  end
  
  def update
    if @cashier.update(cashier_params)
      redirect_to @cashier
    end
  end
  
  def destroy
   if @cashier.cashier_status == true
      @cashier= Cashier.update(params[:id], cashier_status: false) 
      redirect_to cashiers_path
    else
      @cashier= Cashier.update(params[:id], cashier_status: true) 
      redirect_to cashiers_path
    end
  end   
  

  
  private 
    def set_cashier
      @cashier = Cashier.find(params[:id])
    end
    def cashier_params
      params.require(:cashier).permit!
    end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @orders = Order.all
    @orderlines = Orderline.all
  end
  
  def new
    @order = Order.new
    # @orderline = Orderline.new
    # @orderlines = Orderline.new
  end
  
  
  def create
    @order = current_cashier.orders.new(order_params)
    # @orderline = Orderline.new(params.permit(:order_id, :product_id, :order_line_quantity, :order_line_price))
    # @orderlines = Orderline.new(orderline_params)
    # @orderline = Orderline.new(order_id: @order.id, product_id: orderline.product_id, order_line_quantity: orderline.order_line_quantity, order_line_price: orderline.order_line_price)
   
  end
  
  def order_save
    @order = Order.new(order_params)
    # raise @order.inspect
    #@order.orderlines << Orderline.where('order_line_quantity' => params[:order_params]).first
    #@order.save
    if @order.save
      redirect_to @order
    end
  end
  
  def show
  end
  
  def to_s
  end
  
  private
    def set_order
      @order = Order.find_by(id: params[:id])
      #redirect_to orders_path if !@order.present?
    end
    
    def order_params
      params.require(:order).permit!
    end
    
    #def set_orderline
    #  @orderline = Orderline.find_by(id: params[:id])
    #end
    
    #def orderline_params
    #  params.require(:orderline).permit!
    #end
    
    #def set_orderline
     
     # @orderlines = Orderline.find_by(params[:product_id, :order_id, :order_line_quantity, :product_price])
    #end
    
  
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    #product = Product.find(params[:product])
    @product = Product.new(product_name: product_params["product_name"], product_price: product_params["product_price"], product_status:  true)
    if @product.save
        redirect_to @product
    else
      render :new
    end
  end

  def show
    
  end
  
  def to_s
  end
  
  def update
    if @product.update(product_params)
      redirect_to @product
    end
  end
  
  def edit
  end
  
  def destroy
    if @product.product_status == true
      @product = Product.update(params[:id], product_status: false)
      redirect_to products_path
    else
      @product = Product.update(params[:id], product_status: true)
      redirect_to products_path
    end
  end
  
  private
    def set_product
      @product = Product.find(params[:id])
    end
    def product_params
      params.require(:product).permit!
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/index.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Yantramanav" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Condensed" rel="stylesheet">
</head>
<body class ="admin_body">
<div class="container">
<center>
<br>
<Br>
<br>
<br>
<br>
<h1 class = "welcome_admin">Welcome
<br>
Admin.</h1>
<br>
<p class ="date">It is currently</p><div class = "welcome_admin"> <%= DateTime.now.in_time_zone("Singapore").strftime("%B %d %Y") %> </div>
<br>
<p class = "date">and the time is </p>
<div class = "welcome_admin"><%= DateTime.now.in_time_zone("Singapore").strftime("%I:%M %p")%>.</div>
<p class ="date">
<br>
What would you like to do?</p>
<br>
<br>
<div class = "buttons">
     <% if cashier_signed_in? %>
         <%= link_to raw("<i class= 'glyphicon glyphicon-shopping-cart'>" "</i> Show Products"), products_path, class:"btn btn-primary" %>
     <% elsif admin_signed_in? %>
        <%= link_to raw("<i class= 'glyphicon glyphicon-shopping-cart'>" "</i> Show Products"), products_path, class:"btn btn-primary" %>
        <%= link_to raw("<i class= 'glyphicon glyphicon-user'>" "</i> Show cashiers"), cashiers_path, class:"btn btn-primary" %>
     <% end %>
</div>
</div>
</center>
</body>

app/views/cashiers/_form.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
</head>

<body class = "main_admin">
<div class = "welcome_admin">
<div class="text-center form-inputs col-md-offset-3 col-md-6">
    <div class = "date">
    <%= simple_form_for(@cashier, url: @cashier.new_record? ? cashiers_path : cashier_path(@cashier), html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :cashier_name %>
    <%= f.input :email, label: 'E-mail' %>
     <%= link_to raw("<i class= 'glyphicon glyphicon glyphicon-chevron-left'>" "</i> Back"), cashiers_path, class:"btn btn-danger" %>
    <%= f.button :submit, class:"btn btn-success" %>
   
  <% end %>
  </div>
  </div>
</div>
</body>

app/views/cashiers/daily_report.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
</head>
<body class = "main_admin">
<div>
<!-- temp to see font since font is currently white -->
    <center><h3 class = "welcome_admin">DAILY REPORT</h3></center>
    <h7 class ="welcome_admin"><center><i>as of <%= DateTime.now.in_time_zone("Singapore").strftime("%B %d %Y") %></i></center></h7>
    <br>
    <div>
        <table class="table table-bordered">
            <thead class = "welcome_admin">
                <tr>
                    <td><strong>Products</strong></td>
                    <td class="col-md-2"><strong>Quantity Sold</strong></td>
                </tr>
            </thead>
            <tbody class = "date">
                <tr> <!--insert loop for each orderline-->
                    
                </tr>
            </tbody>
        </table>
    </div>
</div>
<%= link_to raw("<i class= 'glyphicon glyphicon-repeat'>" "</i> Back"), cashiers_path, class:"btn btn-danger" %>
</body>

app/views/cashiers/edit.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
</head>
<body class = "main_admin">
<div class = "welcome_admin">
<br>
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <center><h1> EDIT CASHIER </h1></center>
        
        <%= render 'form', cashier: @cashier %>
    </div>
</div>
</div>
</center>
</body>

app/views/cashiers/index.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
</head>
<body class = "main_admin">
<h3 class = "welcome_admin"><center>CASHIERS</center></h3>

<table class="table table-bordered">
    <thead class = "welcome_admin">
        <tr>
            <th>CASHIER</th>
            <th>CASHIER'S EMAIL</th>
            <th>STATUS</th>
            <th>SHOW</th>
            <th>EDIT</th>
            <th>ACTIONS</th>
        </tr>
    </thead>
    <tbody class = "date">
        <% @cashiers.each do |cashier| %>
            <tr>
                <td> <%= cashier.cashier_name %> </td>
                <td> <%= cashier.email %> </td>
                <!--<td> <%= cashier.cashier_status %> </td>-->
                <% if cashier.cashier_status == true %>
                    <td class="text-center"> Active </td>
                <% else %>
                    <td class="text-center"> Deactivated </td>
                <% end %>
                <td class="text-center"> <%= link_to 'Review', cashier, class:"btn btn-info" %> </td>
                <td class="text-center"> <%= link_to 'Edit', edit_cashier_path(cashier), class:"btn btn-primary" %> </td>
                <% if cashier.cashier_status == true %>
                    <td class="text-center"> <%= link_to 'Deactivate', cashier, method: :delete, class:"btn btn-danger", data: { confirm: 'Deactivating: Are you sure?' }  %> </td>
                <% else %>
                     <td class="text-center"> <%= link_to 'Activate', cashier, method: :delete, class:"btn btn-success", data: { confirm: 'Activating: Are you sure?' }  %> </td>
             <% end %>
            </tr>
        <% end %>
        
    </tbody>
</table>

<%= link_to raw("<i class= 'glyphicon glyphicon-user'>" "</i>  Add New Cashiers"), new_cashier_path, class:"btn btn-success" %>
<%= link_to raw("<i class= 'glyphicon glyphicon-list'>" "</i>  Check Daily Sales Report"), cashiers_daily_report_path, class:"btn btn-default" %>
<%= link_to raw("<i class= 'glyphicon glyphicon-repeat'>" "</i> Return to Admin Page"), admins_path, class:"btn btn-danger" %>
</body>

app/views/cashiers/new.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
</head>

<center>
<body class = "main_admin">
<div class = "welcome_admin">
<br>
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <h1> ADD A NEW CASHIER </h1>
        
        <%= render 'form', cashier: @cashier %>
    </div>
</div>
</div>
</center>
</body>

app/views/cashiers/show.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
</head>

<body class = "main_admin">
<div class="col-md-9">
    <div class="row">
        <h3 class = "welcome_admin">Show Cashier</h3>
         <table class="table table-bordered">
            <thead class = "welcome_admin">
                <tr class = "welcome_admin">
                    <td>  CASHIER NAME:  </td>
                    <td>  CASHIER ID: </td>
                    <td>  CASHIER STATUS: </td>
                </tr>
            </thead>
            <tbody>
                <tr class = "date">
                    <td> <%= @cashier.cashier_name %> </td>
                    <td> <%= @cashier.id %></td>
                    <% if @cashier.cashier_status == true %>
                    <td> Active </td>
                    <% else %>
                    <td> Deactivated </td>
                    <% end %>
                    <div class="pull-right">
                        <%= link_to 'Back', cashiers_path, class:"btn btn-danger" %>
                        
                    </div>
                </tr>
            </tbody>
    </div>
</div>
<!--<h3 class = "welcome_admin"><center>Orders</center></h3>-->
<br>
<table class="table table-bordered">
    <thead>
        <tr class = "welcome_admin">
            <th>Order ID</th>
            <th>Total price</th>
            <th>Cash</th>
            <th>OrderList</th>
        </tr>
    </thead>
    <tbody class = "welcome_admin">
        <% @cashier.orders.each do |order| %>
            <tr>
                <% if order.cashier_id = @cashier %>
                <td> <%= order.id %> </td>
                <td><%= order.total_price %> </td>
                <td><%= order.cash %></td>
                <td class="text-center"> <%= link_to 'Review', orders_path , class:"btn btn-info" %> </td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>
</body>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>A S V U S POS SYSTEM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light blue lighten-4" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">A S V U S</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
        <li class = "cc">
           <% if cashier_signed_in? %>
            <li><%= link_to "Orders", orders_path %></li>
          <% elsif admin_signed_in? %>
            <li><%= link_to "Products", products_path %></li> 
            <li><%= link_to "Cashiers", cashiers_path %></li>
            <li><%= link_to "Daily Sales Report", cashiers_daily_report_path %></li>
          <% end %>
        </li>
        </ul>
          <p class="welcome_admin navbar-text pull-right">
           <% if admin_signed_in? %>
            <%= current_admin.name %> |
            <!--<%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |-->
            <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
            <% end %>
          <% if cashier_signed_in? %>
            <strong>Cashier:</strong>
            <strong><%= current_cashier.cashier_name %> </strong> |
            <%= link_to 'Edit profile', edit_cashier_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_cashier_session_path, method: :delete, :class => 'navbar-link'  %>
          <% elsif cashier_signed_in? == false && admin_signed_in? == false %>
            <%= link_to "Login as Admin", new_admin_session_path, :class => 'navbar-link'  %> |
            <%= link_to "Login as Cashier", new_cashier_session_path, :class => 'navbar-link'  %>
          <% end %>
          </p>
        </div>
      </div>
    </nav> 
    
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <% if cashier_signed_in? %>
        <% case current_cashier.valid_password?('password') %>
          <% when true %>
              <p class="alert alert-danger"><strong>NOTICE:</strong> We strongly advise you to change your password. <a href="../cashier/edit">Click here to edit.</a></p>
          <% else %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
  
</html>	

app/views/orders/_form.html.erb
<br>
<body class = "cc">
<div class="col-md-offset-3 col-md-12">
<div class = "welcome_cashier">
<div class="form-inputs">
<%= simple_form_for(@order, html: { class: 'form-horizontal' }) do |f| %>
    <br>
    <br>
    <br>
    <%= f.simple_fields_for :orderlines do |orderline| %>
      <% render 'orderline_fields', f: orderline %>
    <% end %>
    <br>
    <br>
    <div class="links">
      <%= link_to_add_association raw("<i class='glyphicon glyphicon-plus'></i> Add Orderline"), f, :orderlines, class: 'btn btn-primary' %>
    </div>
<% end %>
</div>
</div>
</div>
</div>
</body>

app/views/orders/_orderline_fields.html.erb
<br>
<Br>
<br>
<div class="nested-fields">
<div class = "welcome_cashier">
        <%= f.association :product, collection: Product.where(product_status: true) %>
        <label>Quantity</label>
        <br>
        <%= f.number_field :order_line_quantity %>
        <br>
        <br>
</div>
    <div class="col-md-offset-2 col-md-2">
        <%= link_to_remove_association raw("<i class='glyphicon glyphicon-remove'></i> Remove Orderline"), f, class: "btn btn-danger" %>
        <br>
        <br>
    </div>
</div>

app/views/orders/create.html.erb
<body class = "cc">
<h1 class = "welcome_cashier">CONFIRM ORDER</h1>

<table class="table table-striped">
    <thead class = "welcome_cashier">
        <tr>
            <th>Product</th>
            <th>Price Per Item</th>
            <th>Quantity</th>
            <th>Sub Total</th>
        </tr>
    </thead>
    <tbody class = "cashier">
    <tr>
        <% sum = 0  %>
    <% @order.orderlines.each do |order| %>
    <% if order.product.product_status == true %>
        <td> <%= order.product.product_name %> </td> 
        <td> <%= order.product.product_price %> </td>
        <td> <%= order.order_line_quantity %> </td>
        <td> <%= sub_total = order.product.product_price * order.order_line_quantity %></td>
        <% sum += sub_total %>
        <% @order.total_price = sum %>
    </tr>
    <% end %>
    <% end %> 
    </tbody>
</table>
    <h2 class = "welcome_cashier">TOTAL: <%= sum %></h2> 
<div class="form-inputs col-md-offset-3 col-md-6">
  <%= simple_form_for(@order, url: summary_orders_path(@order), html: { class: 'form-horizontal' }) do |f| %>
  <!-- the reinsertion has to be placed in the submit button here "its this one veron"-->
    <%#<%= f.hidden_field :orderline.product_id, :value => @orderline.product_id %>
    <%#<%= f.hidden_field :order_line_quantity, :value => @orderline.order_line_quantity %>
    <%#<%= f.hidden_field :order_line_price, :value => @orderline.order_line_price %>
    <%#<%= f.hidden_field :orderline_ids, :value => @orderline.order_id %>
    
    <%= f.input :cashier_id %>
    <%= f.input :total_price %>
    <%= f.input :cash %>
    <%= f.button :submit, class:"btn btn-success" %>
    <%= link_to raw("<i class= 'glyphicon glyphicon glyphicon-chevron-left'>" "</i> Back"), orders_path, class:"btn btn-danger" %>
  <% end %>
</div>  
</body>

app/views/orders/index.html.erb
<body class = "cc">
<h3 class = "welcome_cashier"><center>Orders</center></h3>

<%= link_to raw("<i class= 'glyphicon glyphicon-plus'>" "</i>  Add New Order"), new_order_path, class:"btn btn-primary" %>
<br>
<br>

<table class="table table-bordered">
    <thead class = "welcome_cashier">
        <tr>
            <th>Order ID</th>
            <th>Total price</th>
            <th>Cash</th>
            <th>OrderList</th>
        </tr>
    </thead>
    <tbody class = "cashier">
        <% @orders.each do |order| %>
            <tr>
                <td><%= order.id %> </td>
                <td><%= order.total_price %> </td>
                <td><%= order.cash %></td>
                <td class="text-center"> <%= link_to 'Review', order, class:"btn btn-info" %> </td>
            </tr>
        <% end %>
        
    </tbody>
</table>


</body>

app/views/orders/main.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Yantramanav" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Condensed" rel="stylesheet">
</head>

<body class ="cashier_body">
<div class = "container">
<center>
<br>
<Br>
<br>
<h1 class = "welcome_cashier">Welcome</h1>
<br>
<br>
<p class ="cashier">It is currently <%= DateTime.now.in_time_zone("Singapore").strftime("%B %d %Y") %> 
<br>
and the time is <%= DateTime.now.in_time_zone("Singapore").strftime("%I:%M %p")%>.</p>
<p class ="cashier">
<br>
<p class = "cashier">Would you like to check your orders?</p>
<br>
<br>
<div class = "buttons">
     <% if cashier_signed_in? %>
         <%= link_to raw("<i class= 'glyphicon glyphicon-file'>" "</i> Orders"), orders_path, class:"btn btn-danger" %>
    <% end %>
</div>
</center>
</div>
</body>

app/views/orders/new.html.erb
<body class = "cc">
<div class="col-md-offset-3 col-md-6">
<h1 class = "welcome_cashier">New Order</h1>
<div class="form-inputs">
 <%= simple_form_for(@order, html: { class: 'form-horizontal' }) do |f| %>   
    <%= f.simple_fields_for :orderlines do |orderline| %>
      <% render 'orderline_fields', f: orderline %>
    <% end %>
    <br>
    <div class="links">
      <%= link_to_add_association raw("<i class='glyphicon glyphicon-plus'></i> Add Orderlines"), f, :orderlines, class: 'btn btn-primary' %>
    </div>
    <br>
    <div class = "pull-right">
        <%= f.button :submit %>
        <%= link_to 'Back', orders_path, class:"btn btn-danger" %>
    </div>
  <% end %>
</div>
</div>
</body>

app/views/products/index.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
</head>

<body class = "main_admin">
<center><h3 class = "welcome_admin">PRODUCTS</h3></center>
<table class="table table-bordered">
    <thead>
        <tr class = "welcome_admin">
            <th class="text-center col-md-3">PRODUCT NAME </th>
            <th class="text-center col-md-3">PRODUCT PRICE</th>
            <th class="text-center col-md-2">STATUS</th>
            <th colspan="4" class="text-center">ACTIONS</th>
            
        </tr>
    </thead>
    <tbody class = "date ">
        <% @products.each do |products| %>
            <tr>
                <td> <%= products.product_name %> </td>
                <td> <%= products.product_price %> </td>
                <% if products.product_status == true %>
                    <td class="text-center"> Active </td>
                <% else %>
                    <td class="text-center"> Deactivated </td>
                <% end %>
                <td class="text-center"> <%= link_to 'Review', products, class:"btn btn-info" %> </td>
                <td class="text-center"> <%= link_to 'Edit', edit_product_path(products), class:"btn btn-primary" %> </td>
                <% if products.product_status == true %>
                    <td class="text-center"> <%= link_to 'Deactivate', products, method: :delete, class:"btn btn-danger", data: { confirm: 'Removing Product: Are You Sure?' }  %> </td>
                <% else %>
                    <td class="text-center"> <%= link_to 'Activate', products, method: :delete, class:"btn btn-success", data: { confirm: 'Adding Product: Are You Sure?' }  %> </td>
                <% end %>
            </tr> 
        <% end %>
        
    </tbody>
</table>
    <%= link_to raw("<i class= 'glyphicon glyphicon-shopping-cart'>" "</i> Add New Product"), new_product_path, class:"btn btn-success" %>
    <%= link_to raw("<i class= 'glyphicon glyphicon-repeat'>" "</i> Return to Admin Page"), admins_path, class:"btn btn-danger" %>
</body>